image: maven:3.8.4-openjdk-11
stages:
 - test
 - build
services:
  - 'mysql:5.5'
variables:
  MYSQL_DATABASE: "8"
  MYSQL_URL: "jdbc:mysql://mysqlDB:3306/cric"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "root"
  MYSQL_ROOT_PASSWORD: "root"
cache:
  paths:
    - .m2/repository
    - target
maven-test:
 stage: test
 script: "mvn test"
maven-build:
 stage: build
 script: "mvn package"
 artifacts:
  paths:
   - target/*.jar
