# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: "3.9"

services:
  mysqlDB:
    image: "mysql:5"
    container_name: "mysql_5"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - data-volume:/var/lib/mysql
    networks:
      stackRoute:
      
  user-service:
    image: user-service
    container_name: "user-service"
    ports:
      - "8081:8082"
    depends_on:
      - mysqlDB
    networks:
      stackRoute:
      
  favourite-service:
    image: favourite-service
    container_name: "favourite-service"
    ports:
     - "8085:8086"
    depends_on:
      - mysqlDB
    networks:
      stackRoute:
      
networks:
  stackRoute:
volumes:
  data-volume: